services:
  backend:
    build: ./test-backend
    volumes:
      - "./test-backend/:/app/"
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
